### ISSUE TITLE
Tutorial for RBC/Omnisci

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#233]
- [ ] Document and illustrate how to enforce target devices (`devices` kw of `Signature`, `__cpu_` and `__gpu_` prefixes)
- [ ] etc.

**Comment by guilhermeleobas** [comment]
Missing from docs:
- [ ] Document `is_null` for columns and arrays (#239)
- [ ] Template signature: `@omnisci('int32(Column<T>, RowMultiplier, OutputColumn<T>)', T=['double', 'float'])` (#220)
- [ ] String support. Tests are located in `rbc/tests/test_omnisci_text.py` (#225)
- [ ] Document sizer argument: `RowMultiplier`, `Constant` and `ConstantParameter` (#201)
- [ ] Redefine UDF/UDTF functions (#199)
- [ ] Support multiple columns in a single cursor argument (#195)
