### ISSUE TITLE
Implement python operators for omnisci array

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#90]
List of python operators:

- [x] operator.abs - [PR #103](https://github.com/xnd-project/rbc/pull/103)
- [x] operator.add - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.and_ - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] ~operator.attrgetter~
- [ ] operator.concat - needs discussion about the semantics of `a + b`
- [x] operator.contains (`e in a`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.countOf - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] operator.delitem
- [x] operator.eq (`a == e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.floordiv - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.ge (`a >= e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.getitem - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.gt (`a > e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.iadd - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.iand - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] operator.iconcat - same as `operator.concat`
- [x] operator.ifloordiv - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.ilshift - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] ~operator.imatmul~
- [x] operator.imod - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.imul - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] operator.index
- [ ] operator.indexOf
- [ ] operator.inv - not supported by numba
- [ ] operator.invert - not supported by numba
- [x] operator.ior - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.ipow - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.irshift - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.is_ (`a is b`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.is_not (`a is not b`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.isub - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] ~operator.itemgetter~
- [x] operator.itruediv - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.ixor - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.le (`a <= e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] ~operator.length_hint~
- [x] operator.lshift - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.lt (`a < e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] ~operator.matmul~
- [ ] ~operator.methodcaller~
- [x] operator.mod - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.mul - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.ne (`a != e`) - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.neg - [PR #103](https://github.com/xnd-project/rbc/pull/103)
- [ ] operator.not_
- [x] operator.or_ - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.pos - [PR #103](https://github.com/xnd-project/rbc/pull/103)
- [x] operator.pow - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.rshift - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.setitem - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.sub - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [x] operator.truediv - [PR #89](https://github.com/xnd-project/rbc/pull/89)
- [ ] operator.truth
- [x] operator.xor - [PR #89](https://github.com/xnd-project/rbc/pull/89)
